/*
 * API: functions to interconnect game front with back and DB.
 *
 * Daniel José Armas Azar A01786896
 * Guillermo Patricio González Martínez A01787393
 * David Blanco Ortiz A01786713
 * 
 * Use of AI: AI was used to solve some problems with the connection between backend and API
 */

//Function to read and translate generation zones from DB to game
//They are async functions so they can work properly with the connections (also async)

async function initGenerationZones(level, unit) {
    const zones = await fetch(`http://localhost:3000/zonas/${level}`);
    const data = await zones.json();

    let generation_zones = [];

    //Translate the zones from DB to zones game can understand
    for (const row of data) {
        generation_zones.push(new generation_zone(row.coord_x*unit, row.coord_y*unit, row.hostil));
    }
    return generation_zones;
}

//To dealt power-up cards. Reads the power-ups from DB and randomly selects some of them
async function initPowerUps() {
    const res = await fetch(`http://localhost:3000/cartas-powerup/${gameConfig.id_jugador}`);
    const data = await res.json();

    let powerUpInventory = [];
    for (let i = 0; i < 3; i++) {
        let type = data[randomRange(data.length, 0)];
        let card = addCard(0,0,10,10,powerUpInventory,type.nombre,type.duracion_base,type.nivel_actual);
        card.id_carta = type.id_carta;
        card.nivel_actual = type.nivel_actual;
        card.efecto = type.efecto;
    }
    return powerUpInventory;
}

//To dealt platform cards randomly
async function initPlatformCards() {
    const res = await fetch(`http://localhost:3000/cartas-plataforma/${gameConfig.id_jugador}`);
    const data = await res.json();

    let platformInventory = [];
    for (let i = 0; i < 7; i++) {
        let type = data[randomRange(data.length, 0)];
        let card = addCard(0, 0, 8, 8, platformInventory, type.tipo, 5000, type.nivel_actual);
        card.composicion = type.composicion; // the formas JSON
        card.id_carta = type.id_carta; // store the card ID for later use
        card.nivel_actual = type.nivel_actual; // store the required level for this card
        card.ancho_base = type.ancho_base; // store the base width for this card
        card.alto_base = type.alto_base; // store the base height for this card
    }
    return platformInventory;
}

//Function to read and translate platforms from DB to game
async function initPlatforms(auto, zones, unit) {  //auto = is auto_generated?
    const res = await fetch(`http://localhost:3000/plats/${auto}`);
    const platforms = await res.json();

    let actualPlatforms = [];
    let rand = 0;

    //Translates the platforms to autogenerated platforms for the game
    for(let i = 0; i < zones.length; i++) {  //Assigns one platform for each zone
            let zone = zones[i];
            let plat;

            if (i == 0 || i == zones.length - 1) {  //The last zone and first zone share a different platform
                plat = platforms[1];  
            }
            else {
                rand = randomRange(platforms.length, 0);
                plat = platforms[rand];  //Selects a random platform
            }

            for(let j = 0; j < plat.composicion.formas.length; j++) {
                addPlatform(zone.x + plat.composicion.formas[j].x*unit, zone.y + plat.composicion.formas[j].y*unit, plat.composicion.formas[j].base, plat.composicion.formas[j].altura, actualPlatforms, unit, zone.hostil, rand+1, IMG[`p${rand+1}`].xIMG, IMG[`p${rand+1}`].yIMG);
            }
        }
    return actualPlatforms;
}

//To randimly select the level enemies from the DB
async function initEnemies(level){
    let enemyLevel = 1;
    //Assign the level required for the enemies according to the actual level of the game
    if(level >=4 && level <=6){
        enemyLevel = 2;
    }
    else if(level >= 7 && level <=9){
        enemyLevel = 3;
    }
    const res = await fetch(`http://localhost:3000/enemigos/${enemyLevel}`);
    const data = await res.json();
    return data;
}

//Reads the data needed to insert a boss in the game
async function initBoss(level){
    const res = await fetch(`http://localhost:3000/jefe/${level}`);
    const data = await res.json();
    return data;
}

//Function so a new user can sign up
async function register(username, contraseña, edad) {
    const response = await fetch('http://localhost:3000/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, contraseña, edad })
    });
    const data = await response.json();
    if (data.success) {
        alert('Te has registrado exitosamente. ¡Ya puedes iniciar sesión!');
    } else {
        alert(data.error);
    }
}

//Function so a suer can acces to its account
async function login(username, contraseña) {
    const response = await fetch('http://localhost:3000/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, contraseña })
    });
    const data = await response.json();
    if (data.success) {
        //AI was used to change the login from global variables to localStorage
        localStorage.setItem("id_jugador", JSON.stringify(data.id_jugador));
        localStorage.setItem("usuario", JSON.stringify(data.username));
        // gameConfig.id_jugador = data.id_jugador;
        alert('¡Inicio de sesión exitoso, ya puedes jugar!');
    } else {
        alert(data.error);
    }
}

//Function to create a new run in the DB
async function createPartida(id_jugador) {
    const res = await fetch('http://localhost:3000/partida/nueva', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id_jugador })
    });
    const data = await res.json();
    return data.id_partida; // Store this in gameConfig
}

//Function to save the progress of the run, it is called when a level is finished, therefore, it does not save progress within the level.
async function savePartida(id_partida) {
    await fetch('http://localhost:3000/partida/guardar', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            id_partida,
            puntaje_total: gameConfig.score,
            niveles_completados: 1,          // ← always increment by 1
            enemigos_total: gameConfig.enemiesKilled,
            vidas_restantes: gameConfig.lives,
            tiempo_total_seg: gameConfig.elapsedTime
        })
    });
}

//Function to restore the run progress when a player had left and want to continue
async function continuarPartida(id_jugador) {
    const res = await fetch(`http://localhost:3000/partida/continuar/${id_jugador}`);
    const data = await res.json();
    return data; // { found: true, partida: {...} } or { found: false }
}

//Function to put an end to an active run. It is called when a user wins or loses
async function finishPartida(id_partida) {
    await fetch('http://localhost:3000/partida/terminar', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id_partida })
    });
}

//Function to upgrade a card in the user account.
async function upgradeCard(id_jugador, id_carta) {
    await fetch('http://localhost:3000/carta/mejorar', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id_jugador, id_carta })
    });
}