/*
 * BackEnd: to connect interconnect DB and API
 *
 * Daniel José Armas Azar A01786896
 * Guillermo Patricio González Martínez A01787393
 * David Blanco Ortiz A01786713
 */

//Definition of modules
//Imports the required modules
const express = require('express');
const cors = require('cors');
const mysql = require('mysql2');
//Creates the Express server
const app = express();
const port = 3000; //Port the server will listen on
//Enables CORS and JSON request handling
app.use(cors());
app.use(express.json());
//Creates a MySQL connection pool
const pool = mysql.createPool({
    host: '192.168.1.10',
    user: 'root',
    password: 'bl200611',
    database: 'hyperjump'
}).promise();

//Generation zones backend
app.get('/zonas/:level', async (req, res) => {
    try{
    const level = req.params.level;  //Gets level from URL
    //Fetch all zones that belong to this level
    const [zones] = await pool.query('SELECT * FROM ZonaGeneracion WHERE id_nivel = ?', [level]);

    res.json(zones);
    }catch(error){
        console.error('Error fetching generation zones:', error);
        res.status(500).json({ error: 'Error fetching generation zones' });
    }
});

//Platforms autogenerated backend
//Returns platforms filtered by whether they are auto-generated or not
app.get('/plats/:auto', async(req, res) => {
    try{
    //Convert string "true" or "false" to MySQL boolean
    const auto = req.params.auto == "true" ? 1 : 0; //To detect if we want autogenerated or not platforms
    //Fetch platforms matching the auto-generated
    const [plats] = await pool.query('SELECT * FROM Plataforma WHERE es_autogenerada = ?', [auto]);
    res.json(plats);
    }catch(error){
        console.error('Error fetching platforms:', error);
        res.status(500).json({ error: 'Error fetching platforms' });
    }
});

//Returns all power-up cards owned by a specific player with a stored procedure
app.get('/cartas-powerup/:id_jugador', async (req, res) => {
    try{
        const {id_jugador} = req.params
        //Call stored procedure that joins CartaJugador with PowerUp data
        const [powerUps] = await pool.query('CALL GetPlayerPowerUps(?)', [id_jugador]
        );
        //MySQL returns stored procedure results as results[0]
        res.json(powerUps[0]);
    }catch(error){
        console.error('Error fetching power-ups:', error);
        res.status(500).json({ error: 'Error fetching power-ups' });
    }
});

//Returns all platform cards owned by a specific player with stored procedure
app.get('/cartas-plataforma/:id_jugador', async (req, res) => {
    try {
        const { id_jugador } = req.params;
        //Call stored procedure that joins CartaJugador with Plataforma data
        const [results] = await pool.query(
            'CALL GetPlayerPlatforms(?)', [id_jugador]
        );
        //MySQL returns stored procedure results as results[0]
        res.json(results[0]);
    } catch (error) {
        res.status(500).json({ error: 'Error fetching platform cards' });
    }
});

//Creates a new player account in the database
app.post('/register', async (req, res) => {
    try {
        const { username, contraseña, edad } = req.body;
        //Insert new player row into Jugador table
        await pool.query('INSERT INTO Jugador (username, contraseña, edad) VALUES (?, ?, ?)', 
            [username, contraseña, edad]);
        res.json({ success: true });
    } catch (error) {
        //Distinguish between missing fields and duplicate username
        let err;
        if(!username || !contraseña || !edad){
             err = 'Datos incompletos'; 
        } else {err = 'Este Username ya existe';}
        res.status(500).json({ error: err });
    }
});

//Login
//Validates credentials and returns player identity on success
app.post('/login', async (req, res) => {
    try {
        const { username, contraseña } = req.body;
        //Look up the player by username
        const [rows] = await pool.query('SELECT * FROM Jugador WHERE username = ?', [username]);
        //Return error if username does not exist
        if (rows.length === 0) {
            return res.status(401).json({ error: 'Información de inicio de sesión inválida' });
        }
        //Compare submitted password against stored value
        const correctPassword = rows[0].contraseña === contraseña;
        //Return error if password does not match
        if (!correctPassword) {
            return res.status(401).json({ error: 'Información de inicio de sesión inválida' });
        }
        res.json({ success: true, username, id_jugador: rows[0].id_jugador });
    } catch (error) {
        res.status(500).json({ error: 'Información de inicio de sesión inválida' });
    }
});

//Starts a new game session for a player using a stored procedure
app.post('/partida/nueva', async (req, res) => {
    try {
        const { id_jugador } = req.body;
        //We call the stored procedure instead of doing a direct INSERT.
        //This avoids the trigger conflict by handling the logic sequentially.
        await pool.query('CALL iniciar_nueva_partida(?)', [id_jugador]);
        // After the procedure runs, we need to get the ID of the session just created.
        // The procedure uses LAST_INSERT_ID() internally, but we fetch it here for the response.
        const [rows] = await pool.query(
            'SELECT id_partida FROM Partida WHERE id_jugador = ? AND fecha_fin IS NULL ORDER BY fecha_inicio DESC LIMIT 1', 
            [id_jugador]
        );
        res.json({ 
            success: true, 
            id_partida: rows[0].id_partida 
        });
    } catch (error) {
        res.status(500).json({ error: 'Error creating game session' });
    }
});

//Saves game progress to an existing session row
app.put('/partida/guardar', async (req, res) => {
    try {
        const { id_partida, puntaje_total, niveles_completados, 
                enemigos_total, vidas_restantes, tiempo_total_seg } = req.body;
        //Add incoming values on top of existing columns        
        await pool.query(
            `UPDATE Partida SET 
                puntaje_total = puntaje_total + ?,
                niveles_completados = niveles_completados + ?,
                enemigos_total = enemigos_total + ?,
                vidas_restantes = ?,
                tiempo_total_seg = tiempo_total_seg + ?
            WHERE id_partida = ?`,
            [puntaje_total, niveles_completados, enemigos_total, 
             vidas_restantes, tiempo_total_seg, id_partida]
        );
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Error saving game' });
    }
});

//Get unfinished game for a player
//Retrieves the most recent unfinished session for a player
app.get('/partida/continuar/:id_jugador', async (req, res) => {
    try {
        const { id_jugador } = req.params;
        //Find the latest open session, where fecha_fin is NULL = not yet finished
        const [rows] = await pool.query(
            `SELECT * FROM Partida 
             WHERE id_jugador = ? AND fecha_fin IS NULL 
             ORDER BY fecha_inicio DESC LIMIT 1`,
            [id_jugador]
        );
        if (rows.length === 0) return res.json({ found: false }); //No open session
        res.json({ found: true, partida: rows[0] });
    } catch (error) {
        res.status(500).json({ error: 'Error fetching game' });
    }
});

//Marks a game session as finished by setting its end timestamp
app.put('/partida/terminar', async (req, res) => {
    try {
        const { id_partida } = req.body;
        //Stamp fecha_fin with the current time to close the session
        await pool.query(
            'UPDATE Partida SET fecha_fin = CURRENT_TIMESTAMP WHERE id_partida = ?',
            [id_partida]
        );
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Error finishing game' });
    }
});

//Returns all enemies assigned to a given level number with their stats
app.get('/enemigos/:level', async (req, res) => {
    try{
        const level = parseInt(req.params.level); //Obtain level as integer 
        //Join Enemigo with EnemigoNivel aand with Nivel to filter by level number
        const [enemies] = await pool.query('SELECT Enemigo.id_enemigo, Enemigo.nombre, Enemigo.tipo, Enemigo.descripcion, Enemigo.vida_base, Enemigo.daño_base, Enemigo.es_inmortal, Enemigo.rango_ataque, Enemigo.rango_deteccion, EnemigoNivel.cantidad_maxima FROM Enemigo JOIN EnemigoNivel ON Enemigo.id_enemigo = EnemigoNivel.id_enemigo JOIN Nivel ON EnemigoNivel.id_nivel = Nivel.id_nivel WHERE Nivel.numero_nivel = ?', [level]);
        res.json(enemies);

    } catch (error) {
        console.error("ERROR COMPLETO:", error); 
        res.status(500).json({ error: error.message }); 
    }
});

//Returns the boss enemy data for a given level
app.get('/jefe/:level', async (req, res) => {
    try{
        const level = parseInt(req.params.level); //Obtain level as integer
        console.log("Nivel como número:", level);
        // Join JefeNivel with Nivel and with Enemigo, filtering for type "jefe"
        const [boss] = await pool.query(`SELECT Enemigo.id_enemigo, Enemigo.nombre, Enemigo.tipo,Enemigo.descripcion, Enemigo.vida_base, Enemigo.daño_base,Enemigo.es_inmortal, Enemigo.rango_ataque, Enemigo.rango_deteccion, JefeNivel.nombre_jefe FROM JefeNivel JOIN Nivel ON JefeNivel.id_nivel = Nivel.id_nivel JOIN Enemigo ON Enemigo.descripcion = Nivel.dificultad WHERE Nivel.numero_nivel = ? AND Enemigo.tipo = 'jefe'`, [level]);
        res.json(boss);

    } catch (error) {
        console.error("ERROR COMPLETO:", error);
        res.status(500).json({ error: error.message });
    }
});

//Increases a card's level by 1 for a player,maximun of level 4
app.put('/carta/mejorar', async (req, res) => {
    try {
        const { id_jugador, id_carta } = req.body;
        //Increment nivel_actual only if below the maximum of 4
        await pool.query(
            `UPDATE CartaJugador 
             SET nivel_actual = nivel_actual + 1
             WHERE id_jugador = ? AND id_carta = ? 
             AND nivel_actual < 4`,
            [id_jugador, id_carta]
        );
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Error upgrading card' });
    }
});

//Updates player statistics after a game session ends
app.put('/stats/actualizar', async (req, res) => {
    try {
        const { id_jugador, enemigos, cartas_usadas, cartas_mejoradas, 
                victoria, tiempo_seg, nivel_alcanzado, puntuacion } = req.body;
        await pool.query(`
            UPDATE Estadisticas SET
                enemigos_eliminados = enemigos_eliminados + ?,
                cartas_usadas = cartas_usadas + ?,
                cartas_mejoradas = cartas_mejoradas + ?,
                victorias = victorias + ?,
                derrotas = derrotas + ?,
                tiempo_jugado = tiempo_jugado + ?,
                nivel_maximo_alcanzado = GREATEST(nivel_maximo_alcanzado, ?),
                puntuacion_maxima = GREATEST(puntuacion_maxima, ?)
                WHERE id_jugador = ?`, 
                [enemigos, cartas_usadas, cartas_mejoradas,victoria ? 1 : 0, victoria ? 0 : 1,tiempo_seg, nivel_alcanzado, puntuacion, id_jugador]);
        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Error actualizando estadísticas' });
    }
});

//Creates a NivelPartida row for a given session and level with a stored procedure
app.post('/partida/nivelpartida', async (req, res) => {
    const { id_partida, id_nivel } = req.body;
    try {
        await pool.query('CALL crear_nivel_partida(?, ?)', [id_partida, id_nivel]);
        res.json({ mensaje: 'Nivel insertado' });
    } catch (error) {
        res.status(500).json({ error: 'Error al insertar' });
    }
});

//Updates the NivelPartida row with final stats once a level ends
//Used AI to help us succed in the update of the stats
app.put('/stats/actualizar/nivelpartida', async (req, res) => {
    try {
        const { puntaje, tiempo, enemigos, cartas_usadas, 
                multiplicador, completado, id_partida, id_nivel} = req.body;
        await pool.query(`
            UPDATE NivelPartida SET
                puntaje_nivel = ?,
                tiempo_segundos = ?,
                enemigos_eliminados = ?,
                cartas_usadas = ?,
                cartas_no_usadas = ?,
                multiplicador_tiempo = ?,
                completado = ?
                WHERE id_partida = ? AND id_nivel = ?`, 
                [puntaje, tiempo, enemigos, cartas_usadas, 7-cartas_usadas, multiplicador, completado ? 1 : 0, id_partida, id_nivel]);

        res.json({ success: true });
    } catch (error) {
        res.status(500).json({ error: 'Error actualizando estadísticas' });
    }
});

//Insert the dealt cards into the database
app.post('/cartapartida/repartida', async (req, res) => {
    const {cartas, id_partida, id_nivel} = req.body;
    try {
        for(let carta of cartas) {
            let id_carta = carta.id_carta;
            const [rows] = await pool.query('SELECT id_nivel_partida FROM NivelPartida WHERE id_partida = ? AND id_nivel = ? LIMIT 1;', [id_partida, id_nivel] );
            const id_nivel_partida = rows[0].id_nivel_partida;

            await pool.query('CALL init_cartapartida(?, ?)', [id_nivel_partida, id_carta]);
        }
        
        res.json({ mensaje: 'carta contada' });
    } catch (error) {
        res.status(500).json({ error: 'Error al insertar' });
    }
});

//Updates the used registers in the table CartaPartida
app.post('/cartapartida/usada', async (req, res) => {
    const {cartas_id, id_partida, id_nivel} = req.body;
    try {
        for(let id_carta of cartas_id) {
            const [rows] = await pool.query('SELECT id_nivel_partida FROM NivelPartida WHERE id_partida = ? AND id_nivel = ? LIMIT 1;', [id_partida, id_nivel] );
            const id_nivel_partida = rows[0].id_nivel_partida;

            await pool.query('CALL usar_carta(?, ?)', [id_nivel_partida, id_carta]);
        }
        
        res.json({ mensaje: 'carta usada' });
    } catch (error) {
        res.status(500).json({ error: 'Error al insertar' });
    }
});

//---------------------------------------------------------------------------------------------------------------------
//STATS----------------------------------------------------------------------------------------------------------------
//Returns global leaderboard from the top_players view
app.get('/stats/top', async (req, res) => {
    try{
    const [top_players] = await pool.query('SELECT * FROM top_players');
    res.json(top_players);
    }catch(error){
        console.error('Error fetching top_players:', error);
        res.status(500).json({ error: 'Error fetching generation zones' });
    }
});

//Validates credentials before showing private statis
app.post('/stats/user/validation', async (req, res) => {
    try {
        const { username, contraseña } = req.body;
        // Fetch only the password column because is easier to be unique in each username
        const [rows] = await pool.query('SELECT contraseña FROM Jugador WHERE username = ?', [username]);
        if (rows.length === 0) {
            return res.status(401).json({ error: 'Información de inicio de sesión inválida' });
        }

        const correctPassword = rows[0].contraseña === contraseña;
        if (!correctPassword) {
            return res.status(401).json({ error: 'Información de inicio de sesión inválida' });
        }

        res.json({success: true});
    } catch (error) {
        res.status(500).json({ error: 'Información de inicio de sesión inválida' });
    }
});

//Returns detailed stats for a specific user with a stored procedure
app.get('/stats/user', async (req, res) => {
    try{
    //Read username from query
    const username = req.query.username;
    //Stored procedure aggregates stats for this player
    const [stats] = await pool.query('CALL jugador_stats(?)', [username]);
    res.json(stats);
    }catch(error){
        res.status(500).json({ error: 'Error fetching user stats' });
    }
});

//Returns the sum counts across multiple stat columns for the admin dashboard
app.get('/stats/admin/general', async (req, res) => {
    try {
        // List of table and column pairs to sum
        const consults = [
            { table: 'partidas_jugador', col: 'puntaje_total' },
            { table: 'partidas_jugador', col: 'enemigos_total' },
            { table: 'jugadores_estadisticas', col: 'cartas_usadas' },
            { table: 'jugadores_estadisticas', col: 'cartas_mejoradas' },
            { table: 'jugadores_estadisticas', col: 'victorias' },
            { table: 'jugadores_estadisticas', col: 'derrotas' }
        ];

        const general_stats = [];
        //Run count_stats procedure for each pair and collect results
        for (const consult of consults) {
            const [rows] = await pool.query('CALL count_stats(?, ?)', [consult.table, consult.col]);
            general_stats.push(rows[0][0]);
        }
        res.json(general_stats);
    } catch (error) {
        console.error('Error fetching general stats:', error);
        res.status(500).json({ error: 'Error fetching general stats' });
    }
});

//Returns datasets for the admin charts
app.get('/stats/admin/graphics', async (req, res) => {
    try {

        const graphics_stats = [];
        //Sessions grouped by month and day 
        const run_day = await pool.query('SELECT COUNT(A.id_partida) AS runs, DATE_FORMAT(fecha_inicio, "%M") AS month, DATE_FORMAT(fecha_inicio, "%d") AS day FROM partidas_jugador AS A GROUP BY DATE_FORMAT(fecha_inicio, "%M"), DATE_FORMAT(fecha_inicio, "%d")');
        graphics_stats.push({run_day: run_day[0]});
        //Count of started vs completed sessions
        const start_end = await pool.query('SELECT COUNT(A.fecha_inicio) AS iniciadas, COUNT(A.fecha_fin) AS terminadas FROM partidas_jugador AS A');
        graphics_stats.push({start_end: start_end[0]});
        //Average number of sessions per player
        const avg_runs_user = await pool.query('SELECT AVG(partidas) AS promedio_partidas FROM (SELECT COUNT(A.id_partida) AS partidas FROM partidas_jugador AS A GROUP BY A.id_jugador) AS t');
        graphics_stats.push({avg_runs: avg_runs_user[0]});
        //Average time of completed session
        const avg_time_end = await pool.query('SELECT AVG(tiempo) AS promedio_tiempo FROM (SELECT COUNT(A.id_partida) AS tiempo FROM partidas_jugador AS A WHERE A.fecha_fin <> NULL) AS t');
        graphics_stats.push({avg_time: avg_time_end[0]});
        //How many times each card was dealt vs actually used
        const card_dealt_used_plat = await pool.query('SELECT A.id_carta AS id, C.nombre AS nombre, SUM(A.nivel_carta_repartir) AS repartida, SUM(A.veces_usada) AS usada FROM CartaPartida AS A INNER JOIN Carta AS B  USING(id_carta) INNER JOIN Plataforma AS C USING(id_carta) GROUP BY A.id_carta, C.nombre;');
        const card_dealt_used_power = await pool.query('SELECT A.id_carta AS id, C.nombre AS nombre, SUM(A.nivel_carta_repartir) AS repartida, SUM(A.veces_usada) AS usada FROM CartaPartida AS A INNER JOIN Carta AS B  USING(id_carta) INNER JOIN PowerUp AS C USING(id_carta) GROUP BY A.id_carta, C.nombre;');
        graphics_stats.push({card_dealt_used: [card_dealt_used_plat[0], card_dealt_used_power[0]]});

        res.json(graphics_stats);

    } catch (error) {
        console.error('Error fetching general stats:', error);
        res.status(500).json({ error: 'Error fetching general stats' });
    }
});

//Start server
app.listen(port, () => {
    console.log(`Servidor en http://localhost:${port}`);
});
