/*
 * API: functions to interconnect front with back and DB
 *
 * Daniel José Armas Azar A01786896
 * Guillermo Patricio González Martínez A01787393
 * David Blanco Ortiz A01786713
 */

//Function to read and translate generation zones from DB to game
//They are async functions so they can work properly with the connections (also async)

async function initGenerationZones(level) {
    const zones = await fetch(`http://localhost:3000/zonas/${level}`);
    const data = await zones.json();

    let generation_zones = [];

    //Translate the zones from DB to zones game can understand
    for (const row of data) {
        generation_zones.push(new generation_zone(row.coord_x, row.coord_y, row.hostil));
    }
    return generation_zones;
}

async function initCards() {
    const res = await fetch(`http://localhost:3000/powerups`);
    const data = await res.json();

    let powerUpInventory = [];
    for (let i = 0; i < 3; i++) {
        let type = data[randomRange(data.length, 0)];

        addCard(0,0,10,10,powerUpInventory,type.nombre,2000);
    }
    return powerUpInventory;
}

//Function to read and translate platforms from DB to game
async function initPlatforms(auto, zones, unit) {  //auto = is auto_generated?
    const res = await fetch(`http://localhost:3000/plats/${auto}`);
    const platforms = await res.json();

    let actualPlatforms = [];

    //Translates the platforms to autogenerated platforms for the game
    for(let i = 0; i < zones.length; i++) {  //Assigns one platform for each zone
            let zone = zones[i];
            let plat;
            if (i == 0 || i == zones.length - 1) {  //The last zone and first zone share a different platform
                plat = platforms[1];  
            }else if (zone.x == 3200){
                continue;
            }
            else {
                plat = platforms[randomRange(platforms.length, 0)];  //Selects a random platforms
            }

            for(let j = 0; j < plat.composicion.formas.length; j++) {
                addPlatform(zone.x + plat.composicion.formas[j].x * unit, zone.y + plat.composicion.formas[j].y * unit, plat.composicion.formas[j].base, plat.composicion.formas[j].altura, actualPlatforms, unit, zone.hostil);
            }
        }
    return actualPlatforms;
}

async function initEnemies(level){
    console.log("Buscando enemigos para nivel:", level);
    const res = await fetch(`http://localhost:3000/enemigos/${level}`);
    const data = await res.json();
     console.log("ENEMIES DATA:", data);
    return data;
}

async function register(username, contraseña, edad) {
    const response = await fetch('http://localhost:3000/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, contraseña, edad })
    });
    const data = await response.json();
    if (data.success) {
        alert('Registered! You can now log in.');
    } else {
        alert(data.error);
    }
}

async function login(username, contraseña) {
    const response = await fetch('http://localhost:3000/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, contraseña })
    });
    const data = await response.json();
    if (data.success) {
        gameConfig.id_jugador = data.id_jugador;
        startGame(); // your existing function
    } else {
        alert(data.error);
    }
}

async function createPartida(id_jugador) {
    const res = await fetch('http://localhost:3000/partida/nueva', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id_jugador })
    });
    const data = await res.json();
    return data.id_partida; // Store this in gameConfig
}

async function savePartida(id_partida) {
    await fetch('http://localhost:3000/partida/guardar', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            id_partida,
            puntaje_total: gameConfig.score,
            niveles_completados: gameConfig.actualLevel, // assuming actualLevel starts at 1
            enemigos_total: gameConfig.enemiesKilled, // add this to gameConfig
            vidas_restantes: gameConfig.lives,  // add this to gameConfig
            tiempo_total_seg: gameConfig.elapsedTime
        })
    });
}

async function continuarPartida(id_jugador) {
    const res = await fetch(`http://localhost:3000/partida/continuar/${id_jugador}`);
    const data = await res.json();
    return data; // { found: true, partida: {...} } or { found: false }
}

async function finishPartida(id_partida) {
    await fetch('http://localhost:3000/partida/terminar', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id_partida })
    });
}