/*
 * API: functions to interconnect front with back and DB
 *
 * Daniel José Armas Azar A01786896
 * Guillermo Patricio González Martínez A01787393
 * David Blanco Ortiz A01786713
 */

//Function to read and translate generation zones from DB to game
//They are async functions so they can work properly with the connections (also async)
async function initGenerationZones(level) {
    const res = await fetch(`http://localhost:3000/zonas/${level}`);  //It waits for a response (all the not async functions are still running)
    const data = await res.json();

    let generation_zones = [];

    //Translate the zones from DB to zones game can understand
    for (const row of data) {
        generation_zones.push(new generation_zone(row.coord_x, row.coord_y, row.hostil));
    }
    return generation_zones;
}

//Function to read and translate platforms from DB to game
async function initPlatforms(auto, zones, unit) {  //auto = is auto_generated?
    const res = await fetch(`http://localhost:3000/plats/${auto}`);
    const platforms = await res.json();

    let actualPlatforms = [];

    //Translates the platforms to autogenerated platforms for the game
    for(let i = 0; i < zones.length; i++) {  //Assigns one platform for each zone
            let zone = zones[i];

            let plat = platforms[randomRange(platforms.length, 0)];  //Selects a random platforms

            for(let j = 0; j < plat.composicion.formas.length; j++) {
                addPlatform(zone.x + plat.composicion.formas[j].x*unit, zone.y + plat.composicion.formas[j].y*unit, plat.composicion.formas[j].base, plat.composicion.formas[j].altura, actualPlatforms, unit, zone.hostile);
            }
        }
    return actualPlatforms;
}