/*
 * BackEnd: to connect interconnect DB and API
 *
 * Daniel José Armas Azar A01786896
 * Guillermo Patricio González Martínez A01787393
 * David Blanco Ortiz A01786713
 */

//Definition of modules
const express = require('express');
const cors = require('cors');
const mysql = require('mysql2');

const app = express();
const port = 3000;

//Actual host and DB
const host = '192.168.1.8';
const user = 'root';
const pass = 'bl200611';
const db = 'hyperjump';

app.use(cors());

//Generation zones backend
app.get('/zonas/:level', (req, res) => {
    const level = req.params.level;
    
    //Creates the conection
    const connection = mysql.createConnection({
        host: host,
        user: user,
        password: pass,
        database: db
    });

    //Runs the connection
    connection.connect((err) => {
        if (err) throw err;

        //To consult the generation zones
        connection.query(
            'SELECT * FROM ZonaGeneracion WHERE id_nivel = ?', [level], (err, results) => {
                if (err) throw err;

                connection.end();

                res.json(results);
            }
        );
    });
});

//Platforms autogenerated backend
app.get('/plats/:auto', (req, res) => {

    const auto = req.params.auto == "true" ? 1 : 0; //To detect if we want autogenerated or not platforms

    const connection = mysql.createConnection({
        host: host,
        user: user,
        password: pass,
        database: db
    });

    connection.connect((err) => {
        if (err) throw err;

        connection.query('SELECT * FROM Plataforma WHERE es_autogenerada = ?', [auto], (err, results) => {
                if (err) throw err;

                connection.end();
                
                res.json(results);
            }
        );
    });
});

app.listen(port, () => {
    console.log(`Servidor en http://localhost:${port}`);
});